package com.viewfunction.contentRepository.contentBureauImpl;

public interface JCRContentReposityConstant {	
	String SPACE_ROOT_CONTENT_OBJECT_ID="SPACE_ROOT_CONTENT_OBJECT_ID";
	String USER_LOGIN_TIME="USER_LOGIN_TIME";
	String CONTENT_OBJECT_JCR_LOCK_TOKEN="CONTENT_OBJECT_JCR_LOCK_TOKEN";
	String CONTENT_OBJECT_JCR_LOCK_OWNER="CONTENT_OBJECT_JCR_LOCK_OWNER";
	String CONTENT_OBJECT_JCR_LOCK_LOCKTIME="CONTENT_OBJECT_JCR_LOCK_LOCKTIME";
	String METEDATA_CONTENTSPACE="CR_METADATA_CONTENTSPACE";
	String CONTENTSPACE_REGISTER_ROOTCONTENTOBJECT="CONTENTSPACE_REGISTER_ROOTCONTENTOBJECT";
	String CONTENTSPACE_STATUS_ACTIVE="ACTIVE";
	String CONTENTSPACE_STATUS_INACTIVE="INACTIVE";
}
